name: Build and Deploy Vue.js App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Prepare deployment
      run: |
        # Create a temporary directory to hold what we want to deploy
        mkdir -p dist
        # Copy built dist content to this temporary directory
        cp -R frontend/dist/* dist/

    - name: Remove existing dist directory on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_WEBSERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo rm -rf /var/www/html/dist/
          sudo chown ubuntu:www-data /var/www/html/
          sudo chmod 775 /var/www/html/

    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "dist/*"
        target: "/var/www/html/"

    - name: Correct Permissions and Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo chown -R www-data:www-data /var/www/html/
          sudo find /var/www/html/ -type d -exec chmod 755 {} \;
          sudo find /var/www/html/ -type f -exec chmod 644 {} \;
          sudo nginx -s reload
