name: Build and Deploy Vue.js App

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install and Build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Remove existing dist directory and replace
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Remove the existing dist directory
          sudo rm -rf /var/www/html/dist/
          # Ensure the parent directory has correct permissions before SCP transfer
          sudo mkdir -p /var/www/html/dist/
          sudo chown ubuntu:www-data /var/www/html/dist/
          sudo chmod 775 /var/www/html/dist/

    - name: Copy dist to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "frontend/dist/*" 
        target: "/var/www/html/dist/"
    - name: Correct Permissions and Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Correct permissions for the dist directory after deployment
          sudo chown -R www-data:www-data /var/www/html/dist/
          sudo find /var/www/html/dist/ -type d -exec chmod 755 {} \;
          sudo find /var/www/html/dist/ -type f -exec chmod 644 {} \;
          # Reload Nginx to apply any potential configuration changes
          sudo nginx -s reload
